name: eileen_cake
publish_to: 'none'
description: تطبيق كتالوج وطلبات واتساب لمحل ايلين كيك
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.2
  intl: ^0.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/branding/
    - assets/images/categories/
    - assets/images/products/


    - assets/images/promos/
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
